### ISSUE TITLE
Replace/include tuned and tuned-ppd as replacement/alternative to power profiles daemon

### ISSUE THREAD

**Issue by lunelovehearn** [CachyOS/distribution#60]
based on my personal experience, in some hardware configurations, power profiles daemon is useless as plasma won't offer power profiles to the user. replacing it with tuned and tuned-ppd fixes this issue, after installing it and enabling the tuned service. plasma then will correctly offer the power profiles, and advanced users may tweak it from terminal.

there should be a way to offer this to users in case they have this issue with power profiles daemon.

best regards.

**Comment by 1Naim** [comment]
> they have this issue with power profiles daemon

This "issue" stems from the fact that their system doesn't have support for their CPU's scaling driver nor platform profiles (laptops). tuned and by extension tuned-ppd circumvents this by having custom-made profiles instead of what's defined by the ACPI spec.

There's really no good way of including a way to switch to this other than users installing tuned for themselves (maybe a wiki entry?). Generally for the forseeable future I don't think we'll ever switch to tuned, reasons could be limitations that tuned has (doesn't have equivalent of `powerprofilesctl launch`, or the negligible overhead it has over ppd).

**Comment by lunelovehearn** [comment]
then, I think the solution is to add an article to the wiki, with proper information about how to get the power profiles under plasma, on hardware that doesn't support the default power profiles daemon, by using tuned. you may suggest it as a post-install step.
